### ISSUE TITLE
Damnit why can't i find anything that combines markdown files and resolves links between them?

### ISSUE THREAD

**Issue by forivall** [Qard/remark-include#4]
I swear i wrote a script to do this using markdown-it, but i might have deleted it :( or it's hidden somewhere.

**Comment by BrekiTomasson** [comment]
Hey, sorry for the late answer.

I've forked this extension and am rewriting it more or less from scratch as remark-import, since I wanted to add the functionality you're talking about. I also rewrite header levels in the imported document, so that if you've just opened up a `###` header and import a file beginning with a single `#` header, then that single `#` is rebuilt to a `####` instead.

You'll find the fork over at [BrekiTomasson/remark-import](http://github.com/BrekiTomasson/remark-import), although I should warn you that it's still quite a ways from being complete. I should have it in full working order within the next couple of days, however, at which point I'll be publishing it on npmjs.com as well.

**Comment by forivall** [comment]
@BrekiTomasson Thanks! No worries about time, this was more of something I wanted to do while cleaning up documentation at work, so i've just shelved that.
